name: Vistopia
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.1"
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "image/logo.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - image/
    - fonts/

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Black.ttf
          weight: 300
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
